#!/bin/bash
echo "=== EMBED DIR ==="
ls -la /home/zenflow/vibesql/internal/postgres/embed/ 2>/dev/null || echo "embed dir not found"
echo "=== POSTGRES BINS ==="
ls -la /opt/postgres_micro/bin/ 2>/dev/null || echo "/opt/postgres_micro/bin not found"
echo "=== POSTGRES LIB ==="
ls -la /opt/postgres_micro/lib/ 2>/dev/null || echo "/opt/postgres_micro/lib not found"
echo "=== POSTGRES SHARE ==="
ls -d /opt/postgres_micro/share/ 2>/dev/null && echo "share dir exists" || echo "/opt/postgres_micro/share not found"
echo "=== BUILD DIR ==="
ls -la /home/zenflow/vibesql/build/ 2>/dev/null | grep -E "initdb|pg_ctl|libpq|share"
echo "=== DOCKER IMAGES ==="
docker images 2>/dev/null | grep -i postgres || echo "no postgres docker images"
echo "=== GO VERSION ==="
/usr/local/go/bin/go version 2>/dev/null || echo "go not found"
